export const ROUTES = {
  URI: process.env.BACKEND_URL ?? "https://gymappbackend-tb11.onrender.com",
  LOGIN: "/login/",
  LOGOUT: "/logout/",
  GET_USER: "/user/",
  GET_TRAINING: (trainingId: string) => `/user/training/${trainingId}`,
  GET_TRAININGS: "/user/training/",
  GET_EXERCISE_BY_ID: (exerciseId: string) => `/exercise/${exerciseId}`,
  GET_USER_EXERCISES: "/exercise/",
  GET_USER_EXERCISE_BY_SEARCH: (search: string) =>
    `/exercise/search/?search=${search}`,
  GET_IMAGE: (imageName: string) => `/exercise/image/${imageName}`,
  POST_USER: "/user/",
  POST_TRAINING: "/user/training/",
  POST_EXERCISE: "/exercise/",
  PUT_TRAINING: (trainingId: string) => `/user/training/${trainingId}`,
  PUT_EXERCISE: (exerciseId: string) => `/exercise/${exerciseId}`,
  UPLOAD_IMAGE: (exerciseId: string) => `/exercise/${exerciseId}/image`,
  DELETE_TRAINING: (trainingId: string) => `/user/training/${trainingId}`,
  DELETE_EXERCISE: (exerciseId: string) => `/exercise/${exerciseId}`,
};
